name: "Reference Architecture Submission"
description: "Submit a Reference Architecture for Community Review"
title: "[Reference: ]"
labels: ["reference-architecture"]
body:
 - type: markdown
   attributes:
     value: |
       **Purpose of This Issue**
 
       This is a submission to the reference architecture process.
 
       Should maintainers have sensitive, confidential, or private factors and concerns that influence or affect the project, they are encouraged to contact the TOC directly through CNCF Staff, the private-toc mailing list, Slack, or email.
 - type: input
   id: name
   attributes: 
     label: Name
     description: What is the name of this architecture submission?
     placeholder: e.g., My Reference Architecture
   validations:
     required: true
 - type: input
   id: affiliation
   attributes:
     label: Affiliation
     description: Architectures must be submitted by at least one CNCF Member Company
     placeholder: List of Companies
   validations:
     required: true
 - type: textarea
   id: description
   attributes:
     label: Organizational Description
     description: Describe your Organization 
     placeholder: A brief description of your organization. e.g. a paragraph from an about page on your company's website
   validations:
     required: true
 - type: textarea
   id: team
   attributes:
     label: Team Description
     description: Describe your Team
     placeholder: Do you work for a central IT organization in your company?  or for a team of a specific department?
   validations:
     required: true
 - type: textarea
   id: platform-topology-internal
   attributes:
     label: Internal Topology
     description: Describe your Internal Platform Engineering Team Topology
     placeholder: TBD
   validations:
     required: true
 - type: textarea
   id: platform-topology-external
   attributes:
     label: External Topology
     description: Describe your External Platform Engineering Team Topology
     placeholder: TBD
   validations:
     required: true
